import { useState } from "react";

const projects = [
  { id: "detection", no: "01", type: "SECURITY / LAB", title: "Detection engineering lab", text: "Writing and publishing custom Sigma rules for a homelab detection system.", status: "ACTIVE", tags: ["Sigma", "LEQL", "Ubuntu"] },
  { id: "homelab", no: "02", type: "INFRASTRUCTURE", title: "Self-hosted homelab", text: "A documented Ubuntu host for learning, shipping, and breaking things on purpose.", status: "IN PROGRESS", tags: ["Docker", "Linux", "Networking"] },
  { id: "portfolio", no: "03", type: "INTERFACE", title: "Portfolio dashboard", text: "A working record of the decisions, tools, and experiments behind the system.", status: "COMPLETE", tags: ["React", "TypeScript", "UI"] },
  { id: "cert", no: "04", type: "FOUNDATION", title: "Security+ study archive", text: "Notes, diagrams, and field guides from the certification process.", status: "COMPLETE", tags: ["CompTIA", "Research"] },
];

export function ExploreRadialPortfolio() {
  const [active, setActive] = useState("detection");
  const [tab, setTab] = useState("overview");
  const [menu, setMenu] = useState(false);
  const selected = projects.find((project) => project.id === active) ?? projects[0];

  const jump = (id: string) => {
    document.getElementById(`radial-${id}`)?.scrollIntoView({ behavior: "smooth" });
    setMenu(false);
  };

  return (
    <div className="radial-shell">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Instrument+Serif:ital@0;1&display=swap');
        .radial-shell{--ink:#18251f;--forest:#284b3b;--moss:#6d876b;--line:#becabb;--cream:#f2f0e5;--sun:#d3a746;--rust:#b9684e;min-height:100vh;background:var(--cream);color:var(--ink);font-family:'DM Mono',monospace;overflow:hidden}
        .radial-shell *{box-sizing:border-box}.radial-shell button{font:inherit;color:inherit}.radial-shell a{color:inherit;text-decoration:none}
        .radial-shell:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.18;background-image:radial-gradient(var(--moss) .65px,transparent .65px);background-size:8px 8px;z-index:0}
        .radial-inner{position:relative;z-index:1;display:grid;grid-template-columns:250px minmax(0,1fr);min-height:100vh}
        .radial-aside{border-right:1px solid var(--line);padding:27px 22px 23px;display:flex;flex-direction:column;position:sticky;top:0;height:100vh;background:rgba(242,240,229,.88);backdrop-filter:blur(14px)}
        .radial-logo{display:flex;align-items:center;gap:11px;text-transform:uppercase;letter-spacing:.12em;font-size:10px}.radial-logo i{display:block;width:20px;height:20px;border:1px solid var(--forest);border-radius:50%;position:relative}.radial-logo i:after{content:"";position:absolute;background:var(--sun);width:7px;height:7px;border-radius:50%;right:-4px;bottom:-3px}
        .radial-kicker{font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:var(--moss);line-height:1.6}.radial-nav{display:grid;gap:13px;margin-top:74px}.radial-nav button{background:none;border:0;text-align:left;cursor:pointer;font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#718174;padding:0}.radial-nav button:first-child,.radial-nav button:hover{color:var(--rust)}
        .radial-aside-bottom{margin-top:auto;border-top:1px solid var(--line);padding-top:18px;font-size:9px;line-height:1.7;color:#718174}.radial-aside-bottom strong{display:block;color:var(--forest);font-weight:500;margin-bottom:5px}
        .radial-main{min-width:0}.radial-top{display:flex;justify-content:space-between;align-items:center;padding:17px clamp(20px,4vw,65px);border-bottom:1px solid var(--line);font-size:9px;letter-spacing:.1em;text-transform:uppercase;color:#718174}.radial-menu{display:none;background:none;border:0;text-transform:uppercase;font-size:10px;cursor:pointer}
        .radial-hero{padding:clamp(58px,8vw,118px) clamp(20px,6vw,90px) 54px;border-bottom:1px solid var(--line);display:grid;grid-template-columns:minmax(0,1.4fr) minmax(260px,.6fr);gap:70px;align-items:end}.radial-eyebrow{font-size:10px;letter-spacing:.15em;text-transform:uppercase;color:var(--rust)}.radial-hero h1{font-family:'Instrument Serif',serif;font-size:clamp(70px,11vw,158px);font-weight:400;letter-spacing:-.07em;line-height:.78;margin:22px 0 31px}.radial-hero h1 em{color:var(--rust);font-style:italic}.radial-copy{font-size:11px;line-height:1.9;color:#647268;max-width:490px;margin:0}.radial-actions{display:flex;gap:9px;margin-top:27px;flex-wrap:wrap}.radial-actions button{border:1px solid var(--forest);background:var(--forest);color:var(--cream);padding:12px 14px;font-size:9px;letter-spacing:.08em;text-transform:uppercase;cursor:pointer}.radial-actions button.alt{background:transparent;color:var(--forest);border-color:var(--line)}
        .radial-orbit{border:1px solid var(--line);border-radius:50%;aspect-ratio:1;max-width:310px;margin-left:auto;position:relative;display:grid;place-items:center;background:rgba(255,255,255,.16)}.radial-orbit:before,.radial-orbit:after{content:"";position:absolute;border:1px solid var(--line);border-radius:50%}.radial-orbit:before{inset:17%}.radial-orbit:after{inset:34%;border-color:var(--sun)}.radial-core{font-size:9px;text-align:center;line-height:1.6;text-transform:uppercase;letter-spacing:.08em}.radial-core b{display:block;font-family:'Instrument Serif',serif;font-size:30px;font-weight:400;letter-spacing:-.03em}.radial-node{position:absolute;width:8px;height:8px;border-radius:50%;background:var(--rust)}.radial-node.one{top:14%;right:22%}.radial-node.two{bottom:19%;left:13%;background:var(--moss)}.radial-node.three{top:49%;right:-4px;background:var(--sun)}
        .radial-statbar{display:grid;grid-template-columns:repeat(4,1fr);margin-top:53px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);grid-column:1/-1}.radial-stat{padding:16px 12px;border-right:1px solid var(--line)}.radial-stat:last-child{border:0}.radial-stat b{font-family:'Instrument Serif',serif;font-size:27px;font-weight:400;display:block}.radial-stat span{font-size:8px;color:#718174;letter-spacing:.08em;text-transform:uppercase;display:block;margin-top:6px}
        .radial-work{padding:78px clamp(20px,6vw,90px)}.radial-work-head{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid var(--line);padding-bottom:22px;margin-bottom:0}.radial-work h2,.radial-archive h2,.radial-contact h2{font-family:'Instrument Serif',serif;font-size:clamp(44px,6vw,80px);font-weight:400;line-height:.86;letter-spacing:-.05em;margin:13px 0 0}.radial-work-head p{max-width:300px;margin:0;color:#718174;font-size:10px;line-height:1.8}.radial-projects{display:grid;grid-template-columns:1.5fr .85fr;gap:0;border-bottom:1px solid var(--line)}.radial-project{display:grid;grid-template-columns:42px 1fr auto;gap:18px;align-items:start;border-bottom:1px solid var(--line);padding:25px 0;text-align:left;background:none;border-left:0;border-right:0;border-top:0;cursor:pointer}.radial-project:nth-last-child(-n+2){border-bottom:0}.radial-project:hover,.radial-project.selected{color:var(--rust)}.radial-project-no{font-size:10px;color:var(--moss);padding-top:4px}.radial-project h3{font-family:'Instrument Serif',serif;font-size:28px;font-weight:400;line-height:1;margin:0 0 9px;color:var(--ink)}.radial-project:hover h3,.radial-project.selected h3{color:var(--rust)}.radial-project p{font-size:10px;line-height:1.7;color:#718174;margin:0;max-width:460px}.radial-status{font-size:8px;letter-spacing:.08em;color:var(--moss);padding-top:4px}.radial-taglist{display:flex;gap:6px;flex-wrap:wrap;margin-top:14px}.radial-tag{border:1px solid var(--line);padding:4px 6px;font-size:8px;color:var(--moss)}
        .radial-record{grid-column:2;grid-row:1 / span 4;border-left:1px solid var(--line);padding:25px 0 25px 27px;margin-left:28px;display:flex;flex-direction:column;justify-content:space-between;min-height:100%}.radial-record-label{font-size:9px;text-transform:uppercase;letter-spacing:.12em;color:var(--rust)}.radial-record h3{font-family:'Instrument Serif',serif;font-size:39px;line-height:.93;font-weight:400;margin:18px 0}.radial-record p{font-size:10px;line-height:1.8;color:#718174;margin:0}.radial-record-mark{font-family:'Instrument Serif',serif;font-size:94px;color:var(--line);line-height:.7;text-align:right;margin-top:30px}
        .radial-archive{background:var(--forest);color:var(--cream);padding:78px clamp(20px,6vw,90px)}.radial-archive .radial-eyebrow{color:#e2b36d}.radial-archive h2{margin-bottom:40px}.radial-tabs{display:flex;gap:24px;border-bottom:1px solid #587060}.radial-tabs button{background:none;border:0;padding:0 0 13px;color:#aab8a8;font-size:9px;text-transform:uppercase;letter-spacing:.1em;cursor:pointer}.radial-tabs button.active{color:var(--cream);border-bottom:2px solid #e2b36d}.radial-archive-body{display:grid;grid-template-columns:1.1fr .9fr;gap:70px;padding-top:30px}.radial-archive-body p{font-family:'Instrument Serif',serif;font-size:27px;line-height:1.18;margin:0}.radial-archive-body ul{list-style:none;padding:0;margin:0;font-size:10px;line-height:2.3;color:#b6c3b4}.radial-archive-body li:before{content:"—";color:#e2b36d;margin-right:10px}
        .radial-contact{padding:82px clamp(20px,6vw,90px);display:grid;grid-template-columns:1fr .8fr;gap:80px}.radial-contact h2{font-size:clamp(43px,6vw,76px);margin:13px 0 19px}.radial-contact p{font-size:10px;line-height:1.8;color:#718174;max-width:410px;margin:0}.radial-contact a{align-self:end;justify-self:end;border-bottom:1px solid var(--rust);font-size:9px;text-transform:uppercase;padding-bottom:8px}.radial-footer{border-top:1px solid var(--line);padding:18px clamp(20px,6vw,90px);display:flex;justify-content:space-between;color:#718174;font-size:8px;letter-spacing:.1em;text-transform:uppercase}
        @media(max-width:780px){.radial-inner{display:block}.radial-aside{display:none}.radial-top{position:sticky;top:0;z-index:3;background:rgba(242,240,229,.9)}.radial-menu{display:block}.radial-menu:after{content:' / index';color:var(--rust)}.radial-hero{grid-template-columns:1fr;gap:35px}.radial-orbit{margin:0 auto;max-width:220px}.radial-statbar{grid-template-columns:repeat(2,1fr)}.radial-stat:nth-child(2){border-right:0}.radial-stat:nth-child(-n+2){border-bottom:1px solid var(--line)}.radial-work-head{display:block}.radial-work-head p{margin-top:20px}.radial-projects{display:block}.radial-project{grid-template-columns:32px 1fr auto}.radial-record{border-left:0;border-top:1px solid var(--line);padding:25px 0;margin:0;min-height:260px}.radial-archive-body,.radial-contact{grid-template-columns:1fr;gap:30px}.radial-contact a{justify-self:start}.radial-footer{display:block;line-height:2.2}}
      `}</style>
      <div className="radial-inner">
        <aside className="radial-aside"><div className="radial-logo"><i /> Torianna / field notes</div><nav className="radial-nav"><span className="radial-kicker">Navigation</span><button onClick={() => jump("work")}>01 / Projects</button><button onClick={() => jump("archive")}>02 / Homelab</button><button onClick={() => jump("contact")}>03 / Contact</button></nav><div className="radial-aside-bottom"><strong>Operator profile</strong>Chicago, IL<br />Defensive security<br /><span style={{color:"var(--moss)"}}>● Lab active</span></div></aside>
        <main className="radial-main">
          <div className="radial-top"><span>Security operations / personal record</span><button className="radial-menu" onClick={() => setMenu(!menu)}>Index</button></div>
          {menu && <div style={{position:"fixed",top:48,right:20,zIndex:4,background:"var(--cream)",border:"1px solid var(--line)",padding:"16px 18px",display:"grid",gap:12,fontSize:10}}><button onClick={() => jump("work")}>01 / Projects</button><button onClick={() => jump("archive")}>02 / Homelab</button><button onClick={() => jump("contact")}>03 / Contact</button></div>}
          <header className="radial-hero"><div><div className="radial-eyebrow">Working record / no. 024</div><h1>Portfolio<br /><em>Dashboard</em></h1><p className="radial-copy">I’m Torianna, a cybersecurity graduate who learns by building systems, breaking them, and understanding why. This is the working record.</p><div className="radial-actions"><button onClick={() => jump("work")}>Inspect projects →</button><button className="alt" onClick={() => jump("archive")}>Open archive</button></div></div><div className="radial-orbit"><span className="radial-node one" /><span className="radial-node two" /><span className="radial-node three" /><div className="radial-core"><b>03</b>systems<br />in orbit</div></div><div className="radial-statbar"><div className="radial-stat"><b>03</b><span>projects shipped</span></div><div className="radial-stat"><b>01</b><span>certification earned</span></div><div className="radial-stat"><b>24/7</b><span>self-hosted uptime</span></div><div className="radial-stat"><b>LEQL + Σ</b><span>detection rules</span></div></div></header>
          <section id="radial-work" className="radial-work"><div className="radial-work-head"><div><div className="radial-eyebrow">01 / Findings index</div><h2>Projects</h2></div><p>A dashboard-style index of work shipped, still active, and documented as the system grows.</p></div><div className="radial-projects">{projects.map((project) => <button key={project.id} className={`radial-project ${active === project.id ? "selected" : ""}`} onClick={() => setActive(project.id)}><span className="radial-project-no">{project.no}</span><span><h3>{project.title}</h3><p>{project.text}</p><span className="radial-taglist">{project.tags.map((tag) => <span className="radial-tag" key={tag}>{tag}</span>)}</span></span><span className="radial-status">{project.status}</span></button>)}<aside className="radial-record"><span className="radial-record-label">Selected record / {selected.no}</span><div><h3>{selected.title}</h3><p>{selected.text} Click any project to inspect its field notes and tools.</p></div><div className="radial-record-mark">↗</div></aside></div></section>
          <section id="radial-archive" className="radial-archive"><div className="radial-eyebrow">02 / Infrastructure</div><h2>Homelab<br /><em>control room</em></h2><div className="radial-tabs">{["overview", "build log", "notes"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div><div className="radial-archive-body"><p>{tab === "overview" ? "Explore the website infrastructure separately from the security detection system running on the same Ubuntu host." : tab === "build log" ? "A quiet history of systems assembled, tested, and made understandable." : "Short notes from the workbench: what changed, what failed, and what shipped."}</p><ul><li>Ubuntu host / dedicated</li><li>Detection lab / documented</li><li>Website infrastructure / active</li><li>No live attack telemetry</li></ul></div></section>
          <section id="radial-contact" className="radial-contact"><div><div className="radial-eyebrow">Contact / handoff</div><h2>Want to inspect the work?</h2><p>The best conversations are about the decisions behind the system. Reach out for project context, write-ups, or a walkthrough of the lab.</p></div><a href="https://www.linkedin.com/in/torianna" target="_blank" rel="noreferrer">Connect on LinkedIn ↗</a></section>
          <footer className="radial-footer"><span>Portfolio / field notes</span><span>Chicago, IL / 2025</span></footer>
        </main>
      </div>
    </div>
  );
}

export default ExploreRadialPortfolio;