import { useState } from "react";

const projects = [
  { id: "detection", label: "01", type: "SECURITY / LAB", title: "Detection engineering lab", text: "Writing and publishing custom Sigma rules for a homelab detection system.", status: "active", tags: ["Sigma", "LEQL", "Ubuntu"] },
  { id: "homelab", label: "02", type: "INFRASTRUCTURE", title: "Self-hosted homelab", text: "A documented Ubuntu host for learning, shipping, and breaking things on purpose.", status: "in progress", tags: ["Docker", "Linux", "Networking"] },
  { id: "portfolio", label: "03", type: "INTERFACE", title: "Portfolio dashboard", text: "A working record of the decisions, tools, and experiments behind the system.", status: "complete", tags: ["React", "TypeScript", "UI"] },
  { id: "cert", label: "04", type: "FOUNDATION", title: "Security+ study archive", text: "Notes, diagrams, and field guides from the certification process.", status: "complete", tags: ["CompTIA", "Research"] },
];

const tabs = ["overview", "build log", "notes"];

export function ExploreCobaltPortfolio() {
  const [active, setActive] = useState("detection");
  const [tab, setTab] = useState("overview");
  const [menuOpen, setMenuOpen] = useState(false);

  const scrollTo = (id: string) => {
    document.getElementById(`cobalt-${id}`)?.scrollIntoView({ behavior: "smooth" });
    setMenuOpen(false);
  };

  return (
    <div className="cobalt-shell">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&display=swap');
        .cobalt-shell{--ink:#10233f;--muted:#60718b;--line:#c7d5e5;--paper:#edf5fb;--paper2:#dceaf7;--blue:#1854a3;--coral:#d7674b;--ice:#f8fbfd;min-height:100vh;background:var(--paper);color:var(--ink);font-family:'DM Mono',monospace;overflow:hidden}
        .cobalt-shell *{box-sizing:border-box}.cobalt-shell button{font:inherit;color:inherit}.cobalt-shell a{color:inherit;text-decoration:none}
        .cobalt-shell:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.4;background-image:linear-gradient(120deg,transparent 0 48%,rgba(24,84,163,.035) 48.2% 48.4%,transparent 48.6%),radial-gradient(#7693b1 .55px,transparent .55px);background-size:130px 130px,8px 8px;z-index:0}
        .cobalt-content{position:relative;z-index:1}.cobalt-nav{height:74px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 clamp(20px,5vw,72px);background:rgba(237,245,251,.88);backdrop-filter:blur(14px);position:sticky;top:0;z-index:5}
        .cobalt-mark{display:flex;align-items:center;gap:12px;font-size:11px;letter-spacing:.12em;text-transform:uppercase}.cobalt-mark-dot{width:17px;height:17px;background:var(--blue);box-shadow:5px 5px 0 var(--coral);transform:rotate(45deg)}
        .cobalt-nav-links{display:flex;gap:28px;font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}.cobalt-nav-links button,.cobalt-menu{border:0;background:none;cursor:pointer}.cobalt-nav-links button:hover{color:var(--coral)}.cobalt-menu{display:none}
        .cobalt-eyebrow{font-size:10px;letter-spacing:.15em;text-transform:uppercase;color:var(--blue)}.cobalt-hero{max-width:1280px;margin:auto;padding:clamp(60px,10vw,136px) clamp(20px,5vw,72px) 74px;border-bottom:1px solid var(--line)}.cobalt-hero-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:clamp(34px,8vw,130px);align-items:end}.cobalt-hero h1{font-family:Fraunces,serif;font-size:clamp(64px,10vw,148px);font-weight:400;line-height:.8;letter-spacing:-.07em;margin:22px 0 34px}.cobalt-hero h1 em{color:var(--coral);font-style:italic}.cobalt-copy{font-size:12px;line-height:1.9;color:var(--muted);max-width:480px}.cobalt-actions{display:flex;gap:10px;margin-top:28px;flex-wrap:wrap}.cobalt-actions button{cursor:pointer;padding:13px 17px;border:1px solid var(--blue);background:var(--blue);color:var(--ice);font-size:10px;text-transform:uppercase;letter-spacing:.08em}.cobalt-actions button.secondary{background:transparent;color:var(--blue);border-color:var(--line)}
        .cobalt-profile{border:1px solid var(--line);background:rgba(248,251,253,.72);padding:22px;transform:rotate(-1.2deg);box-shadow:9px 9px 0 rgba(24,84,163,.09)}.cobalt-card-head{border-bottom:1px solid var(--line);padding-bottom:14px;display:flex;justify-content:space-between;font-size:10px;color:var(--muted);text-transform:uppercase}.cobalt-profile-list{padding-top:18px;display:grid;gap:17px;font-size:11px}.cobalt-profile-list div{display:flex;justify-content:space-between;gap:20px}.cobalt-profile-list span{color:var(--muted)}.cobalt-status{color:var(--blue)}.cobalt-status:before{content:"●";font-size:8px;margin-right:8px}
        .cobalt-metrics{display:grid;grid-template-columns:repeat(4,1fr);margin-top:62px;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.cobalt-metric{padding:18px 15px;border-right:1px solid var(--line)}.cobalt-metric:last-child{border:0}.cobalt-metric b{display:block;font-family:Fraunces,serif;font-size:27px;font-weight:500}.cobalt-metric span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.08em;margin-top:8px}
        .cobalt-section{max-width:1280px;margin:auto;padding:90px clamp(20px,5vw,72px)}.cobalt-intro{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:38px}.cobalt-section h2{font-family:Fraunces,serif;font-size:clamp(42px,5vw,72px);font-weight:400;line-height:.9;letter-spacing:-.05em;margin:14px 0 0}.cobalt-intro p{max-width:330px;color:var(--muted);font-size:11px;line-height:1.8;margin:0}
        .cobalt-project-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.cobalt-project{border:1px solid var(--line);background:rgba(248,251,253,.55);padding:24px;min-height:220px;text-align:left;cursor:pointer;transition:transform .25s,background .25s,border-color .25s}.cobalt-project:hover,.cobalt-project.selected{background:var(--paper2);border-color:var(--coral);transform:translateY(-4px)}.cobalt-project-top{display:flex;justify-content:space-between;color:var(--blue);font-size:9px;letter-spacing:.08em}.cobalt-project h3{font-family:Fraunces,serif;font-size:28px;font-weight:500;margin:38px 0 10px}.cobalt-project p{font-family:Fraunces,serif;font-size:17px;line-height:1.35;max-width:450px;margin:0;color:#334c69}.cobalt-project-foot{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}.cobalt-tag{font-size:9px;color:var(--blue);border:1px solid #aebfd4;padding:5px 7px}.cobalt-detail{grid-column:1/-1;padding:20px 24px;border:1px solid var(--coral);background:rgba(215,103,75,.07);font-size:10px;line-height:1.8;color:var(--muted)}.cobalt-detail strong{color:var(--ink)}
        .cobalt-archive{background:var(--ink);color:var(--paper);padding:90px max(20px,5vw)}.cobalt-archive-inner{max-width:1136px;margin:auto}.cobalt-archive .cobalt-eyebrow{color:#e49a86}.cobalt-archive h2{font-family:Fraunces,serif;font-weight:400;font-size:clamp(44px,6vw,84px);line-height:.9;margin:16px 0 44px;letter-spacing:-.06em}.cobalt-tabs{display:flex;border-bottom:1px solid #455b78;gap:26px}.cobalt-tabs button{background:none;border:0;padding:0 0 14px;color:#9cadc1;cursor:pointer;font-size:10px;text-transform:uppercase;letter-spacing:.1em}.cobalt-tabs button.active{color:#f8fbfd;border-bottom:2px solid #e49a86}.cobalt-archive-body{display:grid;grid-template-columns:1fr 1fr;gap:50px;padding-top:35px}.cobalt-archive-body p{font-family:Fraunces,serif;font-size:24px;line-height:1.3;margin:0;color:#e3edf7}.cobalt-archive-body ul{list-style:none;padding:0;margin:0;font-size:11px;line-height:2.25;color:#b8c9da}.cobalt-archive-body li:before{content:"↳";color:#e49a86;margin-right:10px}
        .cobalt-contact{max-width:1280px;margin:auto;padding:96px clamp(20px,5vw,72px)}.cobalt-contact-box{border-top:1px solid var(--line);padding-top:22px;display:flex;justify-content:space-between;gap:30px;align-items:end}.cobalt-contact h2{font-family:Fraunces,serif;font-size:clamp(42px,6vw,75px);font-weight:400;line-height:.9;max-width:650px;margin:15px 0}.cobalt-contact p{font-size:11px;color:var(--muted);line-height:1.8;max-width:440px}.cobalt-contact a{border-bottom:1px solid var(--coral);padding-bottom:8px;font-size:10px;text-transform:uppercase;white-space:nowrap}.cobalt-footer{border-top:1px solid var(--line);padding:20px clamp(20px,5vw,72px);display:flex;justify-content:space-between;font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:.1em}
        @media(max-width:760px){.cobalt-nav-links{display:none}.cobalt-menu{display:block;font-size:10px;text-transform:uppercase}.cobalt-nav-links.open{display:flex;position:absolute;left:0;right:0;top:73px;padding:20px;background:var(--paper);border-bottom:1px solid var(--line);flex-direction:column;gap:18px}.cobalt-hero-grid,.cobalt-archive-body{grid-template-columns:1fr}.cobalt-hero h1{font-size:22vw}.cobalt-profile{margin-top:22px}.cobalt-metrics{grid-template-columns:repeat(2,1fr)}.cobalt-metric:nth-child(2){border-right:0}.cobalt-metric:nth-child(-n+2){border-bottom:1px solid var(--line)}.cobalt-project-grid{grid-template-columns:1fr}.cobalt-intro,.cobalt-contact-box{display:block}.cobalt-intro p{margin-top:22px}.cobalt-contact a{display:inline-block;margin-top:18px}.cobalt-footer{display:block;line-height:2.2}}
      `}</style>
      <div className="cobalt-content">
        <nav className="cobalt-nav">
          <div className="cobalt-mark"><span className="cobalt-mark-dot" /> Torianna / field notes</div>
          <button className="cobalt-menu" onClick={() => setMenuOpen(!menuOpen)}>Index +</button>
          <div className={`cobalt-nav-links ${menuOpen ? "open" : ""}`}>
            <button onClick={() => scrollTo("work")}>01 / Work</button><button onClick={() => scrollTo("archive")}>02 / Archive</button><button onClick={() => scrollTo("contact")}>03 / Contact</button>
          </div>
        </nav>
        <header className="cobalt-hero">
          <div className="cobalt-hero-grid">
            <div><div className="cobalt-eyebrow">Security operations / personal record</div><h1>Portfolio<br /><em>Dashboard</em></h1><p className="cobalt-copy">I’m Torianna, a cybersecurity graduate who learns by building systems, breaking them, and understanding why. This is the working record.</p><div className="cobalt-actions"><button onClick={() => scrollTo("work")}>Inspect projects →</button><button className="secondary" onClick={() => scrollTo("archive")}>Open archive</button></div></div>
            <aside className="cobalt-profile"><div className="cobalt-card-head"><span>/ operator profile</span><span>no. 024</span></div><div className="cobalt-profile-list"><div><span>focus</span><b>defensive security</b></div><div><span>detection</span><b className="cobalt-status">lab active</b></div><div><span>response loop</span><b>in progress</b></div><div><span>host</span><b>Ubuntu / dedicated</b></div></div></aside>
          </div>
          <div className="cobalt-metrics"><div className="cobalt-metric"><b>03</b><span>projects shipped</span></div><div className="cobalt-metric"><b>01</b><span>certification earned</span></div><div className="cobalt-metric"><b>24/7</b><span>self-hosted uptime</span></div><div className="cobalt-metric"><b>LEQL + Σ</b><span>detection rules</span></div></div>
        </header>
        <main>
          <section id="cobalt-work" className="cobalt-section"><div className="cobalt-intro"><div><div className="cobalt-eyebrow">01 / Findings index</div><h2>Projects</h2></div><p>A dashboard-style index of work shipped, still active, and documented as the system grows.</p></div><div className="cobalt-project-grid">{projects.map((project) => <button key={project.id} className={`cobalt-project ${active === project.id ? "selected" : ""}`} onClick={() => setActive(project.id)}><div className="cobalt-project-top"><span>{project.label} / {project.type}</span><span>{project.status}</span></div><h3>{project.title}</h3><p>{project.text}</p><div className="cobalt-project-foot">{project.tags.map(tag => <span className="cobalt-tag" key={tag}>{tag}</span>)}</div></button>)}<div className="cobalt-detail"><strong>Selected record / </strong>{projects.find(p => p.id === active)?.title} — click any project to inspect its field notes and tools.</div></div></section>
          <section id="cobalt-archive" className="cobalt-archive"><div className="cobalt-archive-inner"><div className="cobalt-eyebrow">02 / Infrastructure</div><h2>Homelab<br /><em>control room</em></h2><div className="cobalt-tabs">{tabs.map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div><div className="cobalt-archive-body"><p>{tab === "overview" ? "Explore the website infrastructure separately from the security detection system running on the same Ubuntu host." : tab === "build log" ? "A quiet history of systems assembled, tested, and made understandable." : "Short notes from the workbench: what changed, what failed, and what shipped."}</p><ul><li>Ubuntu host / dedicated</li><li>Detection lab / documented</li><li>Website infrastructure / active</li><li>No live attack telemetry</li></ul></div></div></section>
          <section id="cobalt-contact" className="cobalt-contact"><div className="cobalt-eyebrow">Contact / handoff</div><div className="cobalt-contact-box"><div><h2>Want to inspect the work?</h2><p>The best conversations are about the decisions behind the system. Reach out for project context, write-ups, or a walkthrough of the lab.</p></div><a href="https://www.linkedin.com/in/torianna" target="_blank" rel="noreferrer">Connect on LinkedIn ↗</a></div></section>
        </main>
        <footer className="cobalt-footer"><span>Portfolio / field notes</span><span>Chicago, IL / 2025</span></footer>
      </div>
    </div>
  );
}

export default ExploreCobaltPortfolio;