import { useState } from "react";

const projects = [
  { id: "01", title: "Homelab detection lab", kind: "HOMELAB", status: "ACTIVE", summary: "Self-hosted detection stack on a repurposed Surface laptop running Ubuntu.", tools: "CrowdSec · Suricata · Loki · Grafana" },
  { id: "02", title: "Custom Sigma rules", kind: "RESEARCH", status: "ONGOING", summary: "Detection logic connected to the reasoning behind every finding.", tools: "Sigma · GitHub · LEQL" },
  { id: "03", title: "Identity + awareness", kind: "FIELD WORK", status: "DOCUMENTED", summary: "SSO rollouts and phishing simulations for real business environments.", tools: "Entra ID · SAML · KnowBe4" },
];

const timeline = [
  ["06.28", "Connected Loki / Promtail / Grafana", "visibility layer"],
  ["06.19", "Published custom Sigma rule", "detection research"],
  ["06.07", "Deployed CrowdSec on Ubuntu host", "homelab"],
];

export function RefinedOlivePortfolio() {
  const [active, setActive] = useState("01");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const jump = (id: string) => {
    document.getElementById(`refined-${id}`)?.scrollIntoView({ behavior: "smooth" });
    setMobileOpen(false);
  };

  const copyContact = () => {
    navigator.clipboard?.writeText("hello@torianna.tech");
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  };

  return (
    <div className="refined-shell">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap');
        .refined-shell{--bg:#0b100d;--panel:#111813;--panel-hi:#182219;--ink:#e0e4d8;--muted:#849084;--faint:#536052;--line:#29362c;--olive:#c5ca70;--mint:#83ad8d;min-height:100vh;background:var(--bg);color:var(--ink);font-family:Manrope,sans-serif;letter-spacing:-.012em;overflow:hidden}
        .refined-shell *{box-sizing:border-box}.refined-shell button{font:inherit;color:inherit}.refined-shell button,.refined-shell a{cursor:pointer}.refined-shell button:focus-visible,.refined-shell a:focus-visible{outline:1px solid var(--olive);outline-offset:4px}
        .refined-shell:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.16;background-image:linear-gradient(rgba(150,170,120,.06) 1px,transparent 1px),linear-gradient(90deg,rgba(150,170,120,.04) 1px,transparent 1px);background-size:36px 36px;mask-image:linear-gradient(to bottom,#000,transparent 80%)}
        .refined-wrap{position:relative;z-index:1;max-width:1440px;margin:auto}.refined-nav{height:62px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 clamp(18px,4vw,58px);position:sticky;top:0;z-index:5;background:rgba(11,16,13,.88);backdrop-filter:blur(14px)}
        .refined-brand{display:flex;align-items:center;gap:11px;background:none;border:0;text-align:left}.brand-square{height:25px;width:25px;border:1px solid var(--olive);display:grid;place-items:center;color:var(--olive);font:500 12px 'DM Mono'}.brand-copy{font:500 11px 'DM Mono';letter-spacing:.12em}.brand-copy small{display:block;margin-top:2px;color:var(--faint);font-size:8px;letter-spacing:.1em}
        .refined-navlinks{display:flex;gap:29px}.refined-navlinks button,.mobile-toggle{background:none;border:0;color:var(--muted);font:10px 'DM Mono';letter-spacing:.1em;text-transform:uppercase}.refined-navlinks button:hover,.refined-navlinks button.active{color:var(--olive)}.mobile-toggle{display:none}
        .refined-hero{padding:clamp(42px,7vw,100px) clamp(18px,6vw,86px) 45px;border-bottom:1px solid var(--line);background:radial-gradient(ellipse at 75% 10%,#263726 0,transparent 32%)}
        .hero-meta{display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:13px;color:var(--faint);font:9px 'DM Mono';letter-spacing:.1em;text-transform:uppercase}.hero-meta b{color:var(--mint);font-weight:400}
        .hero-grid{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(280px,.7fr);gap:clamp(35px,8vw,128px);align-items:end;padding-top:52px}.hero-kicker,.eyebrow{color:var(--olive);font:10px 'DM Mono';letter-spacing:.18em;text-transform:uppercase}.refined-hero h1{font-size:clamp(60px,8.6vw,130px);line-height:.84;letter-spacing:-.095em;margin:18px 0 29px;font-weight:700}.refined-hero h1 em{font-style:normal;color:var(--olive)}.hero-copy{max-width:540px;color:#aab3a5;font-size:14px;line-height:1.72;margin:0}.hero-actions{display:flex;gap:9px;margin-top:25px;flex-wrap:wrap}.hero-actions button{height:38px;border:1px solid var(--olive);padding:0 14px;font:10px 'DM Mono';letter-spacing:.08em;text-transform:uppercase;transition:transform .2s,background .2s}.hero-actions button:hover{transform:translateY(-2px)}.hero-actions .primary{background:var(--olive);color:#172016}.hero-actions .secondary{background:transparent;color:var(--ink);border-color:var(--line)}
        .operator-card{background:rgba(17,24,19,.9);border:1px solid var(--line);padding:18px;box-shadow:8px 8px 0 rgba(197,202,112,.06)}.operator-head{display:flex;justify-content:space-between;padding-bottom:13px;border-bottom:1px solid var(--line);color:var(--muted);font:9px 'DM Mono';text-transform:uppercase}.operator-head b{font-weight:400;color:var(--olive)}.operator-list{display:grid;gap:16px;margin:18px 0 4px;font:10px 'DM Mono'}.operator-list div{display:flex;justify-content:space-between;gap:18px}.operator-list span{color:var(--faint)}.operator-list strong{font-weight:400;text-align:right}.live{color:var(--mint)}.live:before{content:"";display:inline-block;width:6px;height:6px;margin-right:7px;border-radius:50%;background:var(--mint);animation:refined-pulse 2s ease-in-out infinite}
        .metrics{display:grid;grid-template-columns:repeat(4,1fr);margin-top:48px;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.metric{padding:17px 15px;border-right:1px solid var(--line)}.metric:last-child{border:0}.metric b{display:block;color:var(--olive);font:500 24px 'DM Mono'}.metric span{display:block;margin-top:6px;color:var(--muted);font:9px 'DM Mono';letter-spacing:.08em;text-transform:uppercase}
        .refined-main{padding:0 clamp(18px,6vw,86px)}.refined-section{padding:73px 0;border-bottom:1px solid var(--line)}.section-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:27px}.section-head h2{margin:10px 0 0;font-size:clamp(33px,4.7vw,61px);letter-spacing:-.08em;line-height:.9}.section-note{max-width:325px;margin:0;color:var(--muted);font-size:12px;line-height:1.65}
        .project-layout{display:grid;grid-template-columns:1.28fr .72fr;gap:10px}.project-list{border:1px solid var(--line)}.project-row{width:100%;display:grid;grid-template-columns:42px 1fr auto;gap:17px;align-items:start;text-align:left;background:var(--panel);border:0;border-bottom:1px solid var(--line);padding:21px 22px;transition:background .2s,transform .2s}.project-row:last-child{border:0}.project-row:hover,.project-row.selected{background:var(--panel-hi)}.project-row.selected{box-shadow:inset 3px 0 var(--olive)}.project-num{font:10px 'DM Mono';color:var(--olive)}.project-row h3{margin:0 0 7px;font-size:16px;font-weight:600}.project-row p{margin:0;color:var(--muted);font-size:12px;line-height:1.55;max-width:510px}.project-row small{display:block;margin-top:12px;color:var(--faint);font:9px 'DM Mono';letter-spacing:.04em}.project-status{color:var(--mint);font:9px 'DM Mono';letter-spacing:.08em}.project-detail{border:1px solid var(--line);background:var(--panel);padding:22px;min-height:100%;display:flex;flex-direction:column;justify-content:space-between}.detail-top{display:flex;justify-content:space-between;color:var(--muted);font:9px 'DM Mono';text-transform:uppercase}.detail-bar{height:4px;background:#29362c;margin:28px 0 20px}.detail-bar span{display:block;height:100%;background:var(--olive);width:72%}.project-detail h3{font-size:24px;letter-spacing:-.05em;margin:0 0 10px}.project-detail p{font-size:12px;color:var(--muted);line-height:1.65}.detail-foot{border-top:1px solid var(--line);padding-top:14px;color:var(--faint);font:9px 'DM Mono';line-height:1.7}
        .record-grid{display:grid;grid-template-columns:1fr .9fr;gap:10px}.record-card{border:1px solid var(--line);background:var(--panel);padding:22px}.record-card h3{margin:9px 0 16px;font-size:19px}.record-card p{color:var(--muted);font-size:12px;line-height:1.7;max-width:500px}.stack-line{display:flex;gap:8px;flex-wrap:wrap;margin-top:23px}.stack-line span{border:1px solid #3b4939;color:var(--olive);padding:6px 8px;font:9px 'DM Mono'}.timeline{margin-top:14px}.event{display:grid;grid-template-columns:54px 1fr;gap:12px;border-top:1px solid var(--line);padding:14px 0}.event time{color:var(--olive);font:10px 'DM Mono'}.event b{font-size:11px;font-weight:500}.event small{display:block;color:var(--faint);font:9px 'DM Mono';margin-top:4px}
        .refined-footer{padding:23px clamp(18px,6vw,86px);display:flex;justify-content:space-between;color:var(--faint);font:9px 'DM Mono';letter-spacing:.08em;text-transform:uppercase}.contact-button{background:none;border:0;color:var(--olive);font:inherit;text-transform:uppercase;letter-spacing:inherit}
        @keyframes refined-pulse{0%,100%{opacity:.5}50%{opacity:1}}@media(max-width:820px){.refined-navlinks{display:none}.mobile-toggle{display:block}.refined-navlinks.open{display:flex;position:absolute;top:61px;left:0;right:0;background:var(--bg);border-bottom:1px solid var(--line);padding:18px;flex-direction:column;gap:17px}.hero-grid,.project-layout,.record-grid{grid-template-columns:1fr}.operator-card{margin-top:4px}.project-detail{min-height:230px}.section-head{display:block}.section-note{margin-top:18px}.refined-hero h1{font-size:19vw}}@media(max-width:540px){.hero-meta{line-height:1.8;display:block}.hero-meta span:last-child{display:block}.metrics{grid-template-columns:1fr 1fr;gap:0}.metric:nth-child(2){border-right:0}.metric:nth-child(-n+2){border-bottom:1px solid var(--line)}.project-row{grid-template-columns:30px 1fr;gap:10px;padding:18px 15px}.project-status{grid-column:2}.refined-footer{display:block;line-height:2.2}.refined-section{padding:56px 0}}
      `}</style>
      <div className="refined-wrap">
        <nav className="refined-nav">
          <button className="refined-brand" onClick={() => jump("top")}><span className="brand-square">T</span><span className="brand-copy">TORIANNA<small>SECURITY PORTFOLIO</small></span></button>
          <button className="mobile-toggle" onClick={() => setMobileOpen(!mobileOpen)}>Index {mobileOpen ? "−" : "+"}</button>
          <div className={`refined-navlinks ${mobileOpen ? "open" : ""}`}><button className="active" onClick={() => jump("top")}>00 / Dashboard</button><button onClick={() => jump("projects")}>01 / Work</button><button onClick={() => jump("lab")}>02 / Homelab</button><button onClick={() => jump("contact")}>03 / Contact</button></div>
        </nav>
        <header id="refined-top" className="refined-hero">
          <div className="hero-meta"><span><b>●</b> portfolio system / online</span><span>Last revision / 18 Sep 2026</span></div>
          <div className="hero-grid">
            <div><div className="hero-kicker">Security operations / personal record</div><h1>Build systems.<br /><em>Understand why.</em></h1><p className="hero-copy">I’m Torianna, a cybersecurity graduate working from the practical side of the field: build the lab, inspect the signal, document the decision.</p><div className="hero-actions"><button className="primary" onClick={() => jump("projects")}>Inspect the work →</button><button className="secondary" onClick={() => jump("lab")}>Open lab record</button></div></div>
            <aside className="operator-card"><div className="operator-head"><span>/ operator profile</span><b>record 024</b></div><div className="operator-list"><div><span>focus</span><strong>defensive security</strong></div><div><span>detection</span><strong className="live">lab active</strong></div><div><span>response loop</span><strong>in progress</strong></div><div><span>host</span><strong>Ubuntu / dedicated</strong></div></div></aside>
          </div>
          <div className="metrics"><div className="metric"><b>04</b><span>work records</span></div><div className="metric"><b>01</b><span>certification earned</span></div><div className="metric"><b>24/7</b><span>self-hosted uptime</span></div><div className="metric"><b>06</b><span>lab milestones</span></div></div>
        </header>
        <main className="refined-main">
          <section id="refined-projects" className="refined-section"><div className="section-head"><div><div className="eyebrow">01 / Findings index</div><h2>Selected work</h2></div><p className="section-note">A tighter record of work shipped, still active, and documented as the system grows.</p></div><div className="project-layout"><div className="project-list">{projects.map((project) => <button key={project.id} className={`project-row ${active === project.id ? "selected" : ""}`} onClick={() => setActive(project.id)}><span className="project-num">{project.id}</span><span><h3>{project.title}</h3><p>{project.summary}</p><small>{project.tools}</small></span><span className="project-status">{project.status}</span></button>)}</div><div className="project-detail"><div><div className="detail-top"><span>Selected record / {active}</span><span>evidence log</span></div><div className="detail-bar"><span /></div><h3>{projects.find((p) => p.id === active)?.title}</h3><p>{projects.find((p) => p.id === active)?.summary} The work stays legible: tools, context, and next decision are recorded together.</p></div><div className="detail-foot">STATUS / ACTIVE RECORD<br />NEXT / EXPAND DOCUMENTATION</div></div></div></section>
          <section id="refined-lab" className="refined-section"><div className="section-head"><div><div className="eyebrow">02 / Infrastructure record</div><h2>Homelab control room</h2></div><p className="section-note">One dedicated Ubuntu host for the portfolio, monitoring stack, and the experiments behind it.</p></div><div className="record-grid"><article className="record-card"><div className="eyebrow">System topology</div><h3>Visibility before response.</h3><p>Suricata watches the network. CrowdSec adds threat intelligence. Loki and Grafana make the activity inspectable. The response loop is the next milestone.</p><div className="stack-line"><span>Ubuntu</span><span>Suricata</span><span>CrowdSec</span><span>Loki / Grafana</span></div></article><article className="record-card"><div className="eyebrow">Build log / recent</div><div className="timeline">{timeline.map(([date, title, detail]) => <div className="event" key={title}><time>{date}</time><div><b>{title}</b><small>{detail}</small></div></div>)}</div></article></div></section>
          <section id="refined-contact" className="refined-section"><div className="section-head"><div><div className="eyebrow">03 / Handoff</div><h2>Inspect the decisions.</h2></div><p className="section-note">For project context, write-ups, or a walkthrough of the lab. The best conversations start with the why.</p></div><button className="hero-actions primary" onClick={copyContact}>{copied ? "Copied to clipboard" : "hello@torianna.tech →"}</button></section>
        </main>
        <footer className="refined-footer"><span>Portfolio / evidence-first record</span><span>Chicago, IL / <button className="contact-button" onClick={() => jump("top")}>Back to top ↑</button></span></footer>
      </div>
    </div>
  );
}

export default RefinedOlivePortfolio;