// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/explore-paper-portfolio/ExplorePaperPortfolio.tsx": () => import("../components/mockups/explore-paper-portfolio/ExplorePaperPortfolio.tsx")
};
